# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fitsview.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from .qimageview import QImageView

class Ui_FitsView(object):
    def setupUi(self, FitsView):
        FitsView.setObjectName("FitsView")
        FitsView.resize(896, 553)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FitsView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupInfo = QtWidgets.QGroupBox(FitsView)
        self.groupInfo.setTitle("")
        self.groupInfo.setObjectName("groupInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.groupInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupInfo)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupInfo)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.textImageX = QtWidgets.QLineEdit(self.groupInfo)
        self.textImageX.setReadOnly(True)
        self.textImageX.setObjectName("textImageX")
        self.gridLayout.addWidget(self.textImageX, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupInfo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.textImageY = QtWidgets.QLineEdit(self.groupInfo)
        self.textImageY.setReadOnly(True)
        self.textImageY.setObjectName("textImageY")
        self.gridLayout.addWidget(self.textImageY, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupInfo)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 5, 1, 1)
        self.textPixelValue = QtWidgets.QLineEdit(self.groupInfo)
        self.textPixelValue.setReadOnly(True)
        self.textPixelValue.setObjectName("textPixelValue")
        self.gridLayout.addWidget(self.textPixelValue, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupInfo)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupInfo)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.textWorldRA = QtWidgets.QLineEdit(self.groupInfo)
        self.textWorldRA.setReadOnly(True)
        self.textWorldRA.setObjectName("textWorldRA")
        self.gridLayout.addWidget(self.textWorldRA, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupInfo)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.textWorldDec = QtWidgets.QLineEdit(self.groupInfo)
        self.textWorldDec.setReadOnly(True)
        self.textWorldDec.setObjectName("textWorldDec")
        self.gridLayout.addWidget(self.textWorldDec, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupInfo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.labelZoom = QtWidgets.QLabel(FitsView)
        self.labelZoom.setMinimumSize(QtCore.QSize(101, 101))
        self.labelZoom.setMaximumSize(QtCore.QSize(101, 101))
        self.labelZoom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelZoom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelZoom.setText("")
        self.labelZoom.setScaledContents(True)
        self.labelZoom.setObjectName("labelZoom")
        self.horizontalLayout.addWidget(self.labelZoom)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameToolBar = QtWidgets.QFrame(FitsView)
        self.frameToolBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolBar.setObjectName("frameToolBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameToolBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButton = QtWidgets.QToolButton(self.frameToolBar)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 322, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frameToolBar)
        self.imageView = QImageView(FitsView)
        self.imageView.setObjectName("imageView")
        self.horizontalLayout_2.addWidget(self.imageView)
        self.frameToolInfo = QtWidgets.QFrame(FitsView)
        self.frameToolInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolInfo.setObjectName("frameToolInfo")
        self.horizontalLayout_2.addWidget(self.frameToolInfo)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(FitsView)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.comboCuts = QtWidgets.QComboBox(self.frame)
        self.comboCuts.setObjectName("comboCuts")
        self.horizontalLayout_3.addWidget(self.comboCuts)
        self.spinLoCut = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinLoCut.setMinimum(-999999999.0)
        self.spinLoCut.setMaximum(999999999.0)
        self.spinLoCut.setObjectName("spinLoCut")
        self.horizontalLayout_3.addWidget(self.spinLoCut)
        self.spinHiCut = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinHiCut.setMinimum(-999999999.0)
        self.spinHiCut.setMaximum(999999999.0)
        self.spinHiCut.setObjectName("spinHiCut")
        self.horizontalLayout_3.addWidget(self.spinHiCut)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.comboStretch = QtWidgets.QComboBox(self.frame)
        self.comboStretch.setObjectName("comboStretch")
        self.horizontalLayout_3.addWidget(self.comboStretch)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.comboColormap = QtWidgets.QComboBox(self.frame)
        self.comboColormap.setObjectName("comboColormap")
        self.horizontalLayout_3.addWidget(self.comboColormap)
        self.checkColormapReverse = QtWidgets.QCheckBox(self.frame)
        self.checkColormapReverse.setObjectName("checkColormapReverse")
        self.horizontalLayout_3.addWidget(self.checkColormapReverse)
        spacerItem4 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.checkTrimSec = QtWidgets.QCheckBox(self.frame)
        self.checkTrimSec.setChecked(True)
        self.checkTrimSec.setObjectName("checkTrimSec")
        self.horizontalLayout_3.addWidget(self.checkTrimSec)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_3.setStretch(1, 1)

        self.retranslateUi(FitsView)
        QtCore.QMetaObject.connectSlotsByName(FitsView)

    def retranslateUi(self, FitsView):
        _translate = QtCore.QCoreApplication.translate
        FitsView.setWindowTitle(_translate("FitsView", "Form"))
        self.label.setText(_translate("FitsView", "Image"))
        self.label_2.setText(_translate("FitsView", "X:"))
        self.label_3.setText(_translate("FitsView", "Y:"))
        self.label_7.setText(_translate("FitsView", "Value:"))
        self.label_6.setText(_translate("FitsView", "World"))
        self.label_4.setText(_translate("FitsView", "RA:"))
        self.label_5.setText(_translate("FitsView", "Dec:"))
        self.toolButton.setText(_translate("FitsView", "..."))
        self.label_8.setText(_translate("FitsView", "Cuts:"))
        self.label_9.setText(_translate("FitsView", "Stretch:"))
        self.label_10.setText(_translate("FitsView", "Colormap:"))
        self.checkColormapReverse.setText(_translate("FitsView", "reversed"))
        self.checkTrimSec.setText(_translate("FitsView", "trimsec"))

